name: Validate Flatpaks
permissions:
  contents: read

on:
  pull_request:
    paths:
      - "custom/flatpak/**"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v5

      - name: Set up Flathub
        shell: bash
        run: |
          sudo apt install -y flatpak
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Validate Flatpaks
        shell: bash
        run: |
          echo "Validating flatpak files in custom/flatpak/ directory..."

          set -xeuo pipefail

          find "custom/flatpak" -iname '*\.list*' -print0 | \
            while IFS= read -r -d '' flatpaks_file ; do \
              echo "::group:: ===$(basename "$flatpaks_file")==="
              grep -v "#.*" "$flatpaks_file" | grep -v "^$" | \
                while read -r flatpak ; do \
                  flatpak remote-info --user flathub "${flatpak}"
                done
              echo "::endgroup::"
            done
