name: Validate Flatpaks
permissions:
  contents: read

on:
  pull_request:
    paths:
      - "custom/flatpaks/**"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v5

      - name: Set up Flathub
        shell: bash
        run: |
          sudo apt install -y flatpak
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Validate Flatpaks
        shell: bash
        run: |
          echo "Validating flatpak files in custom/flatpaks/ directory..."

          set -xeuo pipefail

          find "custom/flatpaks" -iname '*.preinstall' -print0 | \
            while IFS= read -r -d '' flatpaks_file ; do \
              echo "::group:: ===$(basename "$flatpaks_file")==="
              # Extract Flatpak app IDs from [Flatpak Preinstall <APP_ID>] sections
              grep "^\[Flatpak Preinstall " "$flatpaks_file" | \
                sed 's/^\[Flatpak Preinstall \(.*\)\]$/\1/' | \
                while read -r flatpak ; do \
                  echo "Checking: ${flatpak}"
                  flatpak remote-info --user flathub "${flatpak}"
                done
              echo "::endgroup::"
            done
